<a href="https://colab.research.google.com/github/hasina1198/ML--Human-activity-recognition/blob/master/RandomForest1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

X_train = pd.read_table("train/X_train.txt", delim_whitespace = True)
y_train = pd.read_table("train/y_train.txt", delim_whitespace = True)
X_test = pd.read_table("test/X_test.txt", delim_whitespace = True)
y_test = pd.read_table("test/y_test.txt", delim_whitespace = True)

In [ ]:
import numpy as np
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
trees = [200, 500, 700]
depth = [300, 500, 600]
f = []

for i in range(0,3):
    for j in range(0,3):
        f.append(model_selection.cross_val_score(RandomForestClassifier(n_estimators=trees[i], max_depth=depth[j]), X_train, y_train, cv=model_selection.KFold(n_splits = 10), scoring = 'f1_macro').mean())
        
n=list(range(0,9))
k = n[f.index(max(f))]+1
tk = np.ceil(k/3)-1
dk = np.remainder(k,3)
if (dk != 0):
    dk-=1
else:
    dk = 2
print("number of trees: ",trees[int (tk)])
print("tree depth: ",depth[dk])

C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector 

C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector 

C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector 

C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Ishaan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


number of trees:  700
tree depth:  600


In [ ]:
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
random = RandomForestClassifier(n_estimators=700, max_depth=00)
random.fit(X_train,y_train)
accuracy = metrics.accuracy_score(y_test, random.predict(X_test))
f1 = metrics.f1_score(y_test, random.predict(X_test), average = 'weighted')
c_m = metrics.confusion_matrix(y_test, random.predict(X_test))
print ("Accuracy: ",accuracy)
print ("F1 Score: ",f1)
print ("Confusion Matrix: ",c_m)
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
Axes3D.plot_surface(ax, np.reshape(f, (-1, 3)), np.reshape(np.array([200,200,200,500,500,500,700,700,700]), (-1, 3)), np.reshape(np.array([300,500,600,300,500,600,300,500,600]), (-1, 3)))

C:\Users\Ishaan\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


Accuracy:  0.9239646978954514
F1 Score:  0.921902156388342
Confusion Matrix:  [[480   5  11   0   0   0]
 [ 31 433   7   0   0   0]
 [ 21  45 354   0   0   0]
 [  0   0   0 431  60   0]
 [  0   0   0  44 487   0]
 [  0   0   0   0   0 537]]
